//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HiTours.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TboMethods {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TboMethods() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HiTours.Core.TboMethods", typeof(TboMethods).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AgencyBalance.
        /// </summary>
        public static string AgencyBalance {
            get {
                return ResourceManager.GetString("AgencyBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticate.
        /// </summary>
        public static string Authenticate {
            get {
                return ResourceManager.GetString("Authenticate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book.
        /// </summary>
        public static string Book {
            get {
                return ResourceManager.GetString("Book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BookingDetails.
        /// </summary>
        public static string BookingDetails {
            get {
                return ResourceManager.GetString("BookingDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CalendarFare.
        /// </summary>
        public static string CalendarFare {
            get {
                return ResourceManager.GetString("CalendarFare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChangeRequestStatus.
        /// </summary>
        public static string ChangeRequestStatus {
            get {
                return ResourceManager.GetString("ChangeRequestStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FareQuote.
        /// </summary>
        public static string FareQuote {
            get {
                return ResourceManager.GetString("FareQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FareRule.
        /// </summary>
        public static string FareRule {
            get {
                return ResourceManager.GetString("FareRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PriceRBD.
        /// </summary>
        public static string PriceRBD {
            get {
                return ResourceManager.GetString("PriceRBD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReleasePNRRequest.
        /// </summary>
        public static string ReleasePNRRequest {
            get {
                return ResourceManager.GetString("ReleasePNRRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SendChange.
        /// </summary>
        public static string SendChange {
            get {
                return ResourceManager.GetString("SendChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ssr.
        /// </summary>
        public static string Ssr {
            get {
                return ResourceManager.GetString("Ssr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket.
        /// </summary>
        public static string Ticket {
            get {
                return ResourceManager.GetString("Ticket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpdateCalendarFareOfDay.
        /// </summary>
        public static string UpdateCalendarFareOfDay {
            get {
                return ResourceManager.GetString("UpdateCalendarFareOfDay", resourceCulture);
            }
        }
    }
}
